# Generated by Django 4.0.1 on 2022-01-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('item_num', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=20)),
                ('item_id', models.CharField(max_length=50)),
                ('item_date', models.CharField(max_length=50)),
                ('item_create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 't_record',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_name', models.CharField(max_length=20)),
                ('user_pwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
